---
services:
  checkcle:
    image: operacle/checkcle:latest
    container_name: checkcle
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/mnt/pb_data
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
