---
collections:
  - name: community.general
    version: 11.3.0
roles:
  - src: https://github.com/ironicbadger/tailscale-routes-fix.git
    type: git
  - src: IronicBadger.docker_compose_generator
    version: 2.0.1
  - name: artis3n.tailscale
    version: v5.0.1
