---
collections:
  - name: community.general
    version: 11.4.0
roles:
  - src: ironicbadger.docker_compose_generator
    version: 2.0.1
  - name: artis3n.tailscale
    version: v5.0.1
  - name: apt_over_https
    src: https://github.com/cisagov/ansible-role-apt-over-https
    version: v2.1.0
