---
collections:
  - name: community.general
    version: 12.1.0
  - name: community.proxmox
    version: 1.5.0
  - name: community.crypto
    version: 3.1.0
  - name: community.docker
    version: 5.0.4
roles:
  - src: ironicbadger.docker_compose_generator
    version: v2.1.1
  - name: artis3n.tailscale
    version: v5.0.1
  - name: apt_over_https
    src: https://github.com/cisagov/ansible-role-apt-over-https
    version: v3.0.0
