---
all:
  vars:
    ansible_user: root
  hosts:
    old-prox-1:
  children:
    cluster1:
      hosts:
        prox-1:
        prox-2:
        quorum-1:
        lb-1:
        lb-2:
        mail:
    cluster2:
      hosts:
        prox-3:
        prox-4:
        quorum-2:
        pihole:
        checkle:
        postiz:
    compose:
      hosts:
        checkle:
        postiz:
        mail:
        test:
    mailcow:
      hosts:
        mail:
    haproxy:
      hosts:
        lb-1:
        lb-2:
    pve:
      hosts:
        prox-1:
        prox-2:
        prox-3:
        prox-4:
    quorum:
      hosts:
        quorum-1:
        quorum-2:
