---
all:
  vars:
    ansible_user: root
  hosts:
    old-prox-1:
  children:
    cluster1:
      hosts:
        prox-1:
        prox-2:
        quorum-1:
        mail:
        ticket:
          ansible_host: pve-1
          ansible_connection: pct_ssh
        #nextcloud:
        #  ansible_host: pve-1
        #  proxmox_vmid: 301
        #  ansible_connection: community.proxmox.proxmox_pct_remote
    cluster2:
      hosts:
        prox-3:
        prox-4:
        quorum-2:
        pihole:
        postiz:
    compose:
      hosts:
        postiz:
        mail:
        test:
        ticket:
    mailcow:
      hosts:
        mail:
    pve:
      hosts:
        prox-1:
        prox-2:
        prox-3:
        prox-4:
    quorum:
      hosts:
        quorum-1:
        quorum-2:
