---
all:
  vars:
    ansible_user: root
    ansible_ssh_common_args="-o StrictHostKeyChecking=no"
  hosts:
    prox-1.hale-gray.ts.net:
    prox-2.hale-gray.ts.net:
    prox-3.hale-gray.ts.net:
    prox-4.hale-gray.ts.net:
    quorum-1:
    quorum-2:
  children:
    cluster1:
      hosts:
        prox-1:
        prox-2:
        quorum-1:
    cluster2:
      hosts:
        prox-3:
        prox-4:
        quorum-2:
