---
all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    prox-1:
    prox-2:
    prox-3:
    prox-4:
    quorum-1:
    quorum-2:
    old-prox-1:
  children:
    cluster1:
      hosts:
        prox-1:
        prox-2:
        quorum-1:
    cluster2:
      hosts:
        prox-3:
        prox-4:
        quorum-2:
