---
all:
  hosts:
    n8n:
    pihole:
    test:
    checkle:
    postiz:
    beszel-lxc:
  children:
    cluster1:
      hosts:
        n8n:
    cluster2:
      hosts:
        pihole:
        test:
        checkle:
        postiz:
        beszel-lxc:
    compose:
      hosts:
        test:
        checkle:
        postiz:
