---
all:
  vars:
    ansible_user: root
  hosts:
    n8n:
    pihole:
    checkle:
    postiz:
    prox-1-mail:
  children:
    cluster1:
      hosts:
        n8n:
    cluster2:
      hosts:
        pihole:
        checkle:
        postiz:
    compose:
      hosts:
        checkle:
        postiz:
