---
all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    n8n:
    pihole:
  children:
    cluster1:
      hosts:
        n8n:
    cluster2:
      hosts:
        pihole:
