---
all:
  vars:
    ansible_user: root
  hosts:
    pihole:
    checkle:
    postiz:
  children:
    cluster1:
      hosts:
        lb-1:
        lb-2:
        mail:
    cluster2:
      hosts:
        pihole:
        checkle:
        postiz:
    compose:
      hosts:
        checkle:
        postiz:
        mail:
    mailcow:
      hosts:
        mail:
    haproxy:
      hosts:
        lb-1:
        lb-2:
