name: "Setup Ansible (composite)"
description: "Common setup for Ansible-based workflows: python setup, pip install, optional ansible-galaxy and tailscale login (assumes checkout already done)"
inputs:
  python-version:
    description: "Python version to setup"
    required: false
    default: "3.x"
  requirements-file:
    description: "Path to pip requirements file"
    required: false
    default: "requirements.txt"
  extra-packages:
    description: "Additional pip packages to install (space-separated)"
    required: false
    default: ""
  galaxy-requirements:
    description: "Path to ansible-galaxy requirements file (optional)"
    required: false
    default: "requirements.yaml"
  ts-oauth-client-id:
    description: "Tailscale OAuth client id (pass as secret)"
    required: false
    default: ""
  ts-oauth-secret:
    description: "Tailscale OAuth secret (pass as secret)"
    required: false
    default: ""
  tailscale-tags:
    description: "Tags to pass to tailscale login action"
    required: false
    default: "tag:ci"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@4f41a90a1f38628c7ccc608d05fbafe701bc20ae
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - name: Install pip requirements
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        if [ -n "${INPUTS_REQUIREMENTS_FILE}" ] && [ -f "${INPUTS_REQUIREMENTS_FILE}" ]; then
          python3 -m pip install -r "${INPUTS_REQUIREMENTS_FILE}"
        fi
        if [ -n "${INPUTS_EXTRA_PACKAGES}" ]; then
          python3 -m pip install ${INPUTS_EXTRA_PACKAGES}
        fi
      env:
        INPUTS_REQUIREMENTS_FILE: ${{ inputs.requirements-file }}
        INPUTS_EXTRA_PACKAGES: ${{ inputs.extra-packages }}

    - name: Install Ansible-Galaxy requirements
      if: ${{ inputs.galaxy-requirements != '' }}
      shell: bash
      run: |
        ansible-galaxy install -r ${INPUTS_GALAXY_REQUIREMENTS} --ignore-errors
      env:
        INPUTS_GALAXY_REQUIREMENTS: ${{ inputs.galaxy-requirements }}

    - name: Tailscale Login
      if: ${{ inputs.ts-oauth-client-id != '' && inputs.ts-oauth-secret != '' }}
      uses: tailscale/github-action@61e1192a01f913c2c4fb01a7e967f5ac613ff3f8
      with:
        oauth-client-id: ${{ inputs.ts-oauth-client-id }}
        oauth-secret: ${{ inputs.ts-oauth-secret }}
        tags: ${{ inputs.tailscale-tags }}
