---
- name: Reboot the system
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 300

- name: Wait for SSH to come back
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 300
