---
all:
  children:
    home:
      hosts:
        carport:
        pdm:
        owfs:
        packer:
        pbs-1:
      children:
        compose:
          hosts:
            compose-1:
            compose-2:
            immich:
            netbox:
            nut:
            cloud-1:
        pve:
          hosts:
            pve-1:
            pve-2:
            pve-3:
    basti:
      hosts:
        basti-1:
    cloud:
      children:
        cluster1:
          hosts:
            prox-1:
            prox-2:
            quorum-1:
            cloud-2-old:
            ticket:
            cloud-2:
            mx-1:
        mailcow:
          hosts:
            mx-1:
        prox:
          hosts:
            prox-1:
            prox-2:
        quorum:
          hosts:
            quorum-1:
        k8s-cl2:
          hosts:
            k8s-cl2-n1:
            k8s-cl2-n2:
            k8s-cl2-n3:
