---
########
# Home #
########
- name: All Home Devices
  hosts: home
  gather_facts: false
  tasks:
    - ansible.builtin.include_tasks: tasks/apt-update.yaml
      tags: patch
    - ansible.builtin.include_tasks: tasks/apt-upgrade.yaml
      tags: patch
    - ansible.builtin.include_tasks: tasks/check-reboot.yaml
      tags: patch
    - ansible.builtin.include_tasks: tasks/apt-cleanup.yaml
      tags: cleanup
    - ansible.builtin.include_tasks: tasks/filesystem-trim.yaml
      tags: cleanup

- name: Docker Compose Update on Compose Hosts
  hosts: compose,prox-arm
  gather_facts: true
  tasks:
    - ansible.builtin.include_tasks: tasks/compose-update.yaml
      # tags: patch
    - ansible.builtin.include_tasks: tasks/docker-prune.yaml
      tags: cleanup

#########
# Basti #
#########
- name: All Devices from Basti
  hosts: basti
  gather_facts: false
  tasks:
    - ansible.builtin.include_tasks: tasks/apt-update.yaml
      tags: patch
    - ansible.builtin.include_tasks: tasks/apt-upgrade.yaml
      tags: patch
    - ansible.builtin.include_tasks: tasks/check-reboot.yaml
      tags: patch
    - ansible.builtin.include_tasks: tasks/apt-cleanup.yaml
      tags: cleanup
    - ansible.builtin.include_tasks: tasks/filesystem-trim.yaml
      tags: cleanup

#########
# Cloud #
#########
- name: All Cloud Hosts
  hosts: cloud
  gather_facts: false
  tasks:
    - ansible.builtin.include_tasks: tasks/apt-update.yaml
      tags: patch
    - ansible.builtin.include_tasks: tasks/apt-upgrade.yaml
      tags: patch
    - ansible.builtin.include_tasks: tasks/check-reboot.yaml
      tags: patch
    - ansible.builtin.include_tasks: tasks/apt-cleanup.yaml
      tags: cleanup
    - ansible.builtin.include_tasks: tasks/filesystem-trim.yaml
      tags: cleanup

- name: MX-1 Mailcow Update
  hosts: mx-1
  gather_facts: true
  tasks:
    - ansible.builtin.include_tasks: tasks/mailcow-update.yaml
      tags: patch
    - ansible.builtin.include_tasks: tasks/docker-prune.yaml
      tags: cleanup

- name: Docker Compose Update on Docker Hosts
  hosts: ticket,cloud-2
  gather_facts: true
  tasks:
    - ansible.builtin.include_tasks: tasks/compose-update.yaml
      # tags: patch
    - ansible.builtin.include_tasks: tasks/docker-prune.yaml
      tags: cleanup
