---
- name: Deploy Docker Compose Stack
  hosts: compose
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present
    
    - name: Ensure docker is installed
      ansible.builtin.package:
        name: docker-ce 
        state: present
    
    - name: Ensure docker compose is installed
      ansible.builtin.package:
        name: docker-compose-plugin
        state: present

    - name: Create Folder /docker if it does not exist
      ansible.builtin.file:
        state: directory
        path: /docker
        mode: '0755'

    - name: Clone this Git Repository to /tmp of destination machine
      ansible.builtin.git:
        repo: 'https://github.com/thost96/infra.git'
        dest: /tmp/infra

    - name: Move docker-compose file to /docker
      ansible.builtin.command:
        cmd: mv /tmp/infra/compose/{{ ansible_hostname }}/* /docker/

    - name: Deploy Docker Compose Stack
      ansible.builtin.command:
        cmd: docker compose -f /docker/docker-compose.yaml up -d

    - name: Cleanup old Docker Images and Containers
      ansible.builtin.command:
        cmd: docker system prune -f

    - name: Remove /tmp/compose folder
      ansible.builtin.file:
        state: absent
        path: /tmp/infra
