---
name: Proxmox Host Updates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0" # Sonntag 12 Uhr

jobs:
  proxmox:
    runs-on: self-hosted #ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tailscale Login
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Perform ansible playbook to deploy
        uses: euclid1990/actions-ansible@v2
        with:
          playbook: playbooks/os-updates.yaml
          inventory: inventory/proxmox.yaml
