---
name: Proxmox Host Updates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0" # Sonntag 12 Uhr

jobs:
  proxmox:
    runs-on: ubuntu-latest #self-hosted #ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible

      - name: Tailscale Login
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Run Ansible Playbook
        run: | 
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory/proxmox.yaml playbooks/os-updates.yaml
