---
name: Proxmox Host Updates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0" # Sonntag 12 Uhr

jobs:
  proxmox:
    runs-on: self-hosted #ubuntu-latest
    steps:
      - name: Tailscale Login
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - uses: actions/checkout@v4
    
      - name: Perform ansible playbook to deploy
        uses: euclid1990/actions-ansible@v2
        with:
          playbook: playbooks/os-updates.yaml
          inventory: inventory/proxmox.yaml

      - name: Ansible Playbook Execution
        uses: arillso/action.playbook@0.2.2
        with:
          inventory: inventory/proxmox.yaml
          playbook: playbooks/os-updates.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
