---
name: Virtual Machine Updates

permissions:
  actions: none
  checks: none # add custom pass/fail checks to the PR
  contents: read # git permissions to repo pull/push
  deployments: none
  issues: none # read/write to repo Issues
  packages: none # read/write to repo Packages (ghcr, gems, npm)
  pull-requests: read # read/write to repo PRs
  repository-projects: none
  security-events: none # read/write to repo Security tab API
  statuses: write # read/write to repo custom statuses and checks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * 0" # Sonntag 14 Uhr

jobs:
  os-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible

      - name: Tailscale Login
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Run OS Updates
        run: |
          ansible-playbook -i inventory/vms.yaml playbooks/os-updates.yaml

  app-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible

      - name: Tailscale Login
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Run Pihole Update
        run: |
          ansible-playbook -i inventory/vms.yaml -l pihole playbooks/pihole-update.yaml

      # - name: Run Nextcloud Update
      #   run: |
      #     ansible-playbook -i inventory/vms.yaml -l nextcloud playbooks/nextcloud-update.yaml

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible

      - name: Tailscale Login
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Run Docker Prune
        run: |
          ansible-playbook -i inventory/vms.yaml -l compose playbooks/docker-prune.yaml
